services:
  app:
    build: .
    container_name: fastapi-app-with-docker
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - '6379:6379'
